### ISSUE TITLE
Images are missing from repo, resulting in broken images in documentation

### ISSUE THREAD

**Issue by madesch** [MicrosoftDocs/ATADocs.es-es#27]
There's a lot of broken image links in the documentation, see attached picture.

![broken image-es](https://user-images.githubusercontent.com/6094593/47615054-33041080-daaa-11e8-96b2-638c2276e6f9.PNG)

When I compared with the original repository (https://github.com/MicrosoftDocs/ATADocs) it seems like there are no pictures at all for ATADocs, and there's a lot missing in ATPDocs.

**Comment by LisandroSu** [comment]
Hello, @madesch

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order be able to address your feedback. Can you please provide more detailed information and clarify your comment? Can you provide us the address of the document with the missing images?

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @madesch
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

This was already fixed in the master branch and is soon to be published:https://docs.microsoft.com/es-es/advanced-threat-analytics/ata-architecture?branch=master

Kind regards,
Microsoft DOCS International Team
@nokura

**Comment by CeciAc** [comment]
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/es-es/advanced-threat-analytics/ata-architecture?branch=live

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
